
namespace ModelGraph.Core
{
    public enum DrawEvent
    { 
        Idle,
        Tap,
        Skim,
        Drag,
        TapEnd,
        CtrlTap,
        ShiftTap,
        CtrlDrag,
        ShiftDrag,
        DoubleTap,
        ContextMenu,

        TopTap, 
        LeftTap, 
        RightTap, 
        BottomTap, 
        TopLeftTap, 
        TopRightTap, 
        BottomLeftTap, 
        BottomRightTap,

        OverviewTap,
        Picker2Tap,
        Picker1Tap,
        Picker1CtrlTap,
        Picker1ShiftTap,
        Picker1Drag,

        Cut,
        Copy,
        Paste,
        Apply,
        Revert,
        Escape,
        Angle22,
        Angle30,
        Recenter,
        RotateLeft,
        RotateRight,
        FlipVertical,
        FlipHorizontal,

        AKey,
        BKey,
        CKey,
        DKey,
        EKey,
        FKey,
        GKey,
        LKey,
        MKey,
        NKey,
        OKey,
        PKey,
        QKey,
        RKey,
        SKey,
        TKey,
        UKey,
        VKey,
        WKey,

        EnterKey,
        EscapeKey,
        UpArrowKey,
        LeftArrowKey,
        RightArrowKey,
        DownArrowKey,
    };
}
