
namespace ModelGraph.Core
{
    public enum DrawEvent : byte
    {
        Idle,

        Btn1,
        Btn2,
        Btn3,
        Btn4,
        Btn5,
        Btn6,
        Btn7,
        Btn8,
        Btn9,
        BtnA,
        BtnB,
        BtnC,
        BtnD,
        BtnE,
        BtnF,
        BtnG,
        BtnH,
        BtnI,
        BtnJ,
        BtnK,

        AKey,
        BKey,
        CKey,
        DKey,
        EKey,
        FKey,
        GKey,
        HKey,
        IKey,
        JKey,
        KKey,
        LKey,
        MKey,
        NKey,
        OKey,
        PKey,
        QKey,
        RKey,
        SKey,
        TKey,
        UKey,
        VKey,
        WKey,
        XKey,
        YKey,
        ZKey,

        Tap,
        Skim,
        Drag,
        TapEnd,
        CtrlTap,
        ShiftTap,
        CtrlDrag,
        ShiftDrag,
        DoubleTap,
        ContextMenu,
        OverviewTap,
        Picker2Tap,
        Picker1Tap,
        Picker1CtrlTap,
        Picker1ShiftTap,
        Picker1Drag,

        EnterKey,
        EscapeKey,
        UpArrowKey,
        DownArrowKey,
        LeftArrowKey,
        RightArrowKey,

        ExecuteAction, //pseudo event initiated by the model to envoke an action
    };
}
